require('conf-bufferline')
require('conf-colorscheme')
require('conf-nvimtree')
require('init-packer')
require('conf-lualine')
require('conf-dashboard')
require("which-key").setup({})
require('conf-toggleterm')
require('conf-telescope')
require('conf-treesitter')
require("nvim-lsp-installer").setup ( {} )
require('conf-cmp')
